export const TYPE_QUESTION = {
  IMAGE_4: '4image',
  VOCABULARY_4: '4vocabulary',
  LISTEN: 'listen',
  READ: 'read',
  FILLWORD: 'FillWord',
  TRANSLATE: 'translate',
  LISTEN_STAGE_2: 'listenStage2',
  READ_STAGE_2: 'readStage2',
  PRONOUNCIACION: 'Pronounciacion',
  CHOICE_MULTI_ANSWER: 'choiceMultiAnswer',
  FILL_WORD_STAGE_3: 'FillWordStage3',
  GRAMMAR: 'Grammar',
  SOUND: 'sound',
};
